### ISSUE TITLE
Error to be caught for VenC

### ISSUE THREAD

**Issue by JeremyBerry** [DenisSalem/VenC#20]
Hello,

I am creating a new template for VenC, it is not finished yet (VenC patterns integration in progress). When I insert the `.:GetEntryTitle:.` pattern in the **header.html** file without using a conditional pattern (such as `.:IfInThread:.`), then when I export the blog with the `venc -xb my_new_template` command, I get the following error message:

> jeremy@PC:~/Jérémy Berry$ venc -xb my_new_template
> VenC: ┌─ Chargement des données...
> VenC: ├─ Pré-traitement du théme et des publications...
> Traceback (most recent call last):
>   File "/home/jeremy/.local/bin/venc", line 4, in <module>
>     \_\_import\_\_('pkg_resources').run_script('VenC==2.0.0', 'venc')
>   File "/usr/lib/python3/dist-packages/pkg_resources/\_\_init\_\_.py", line 667, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib/python3/dist-packages/pkg_resources/\_\_init\_\_.py", line 1470, in run_script
>     exec(script_code, namespace, namespace)
>   File "/home/jeremy/.local/lib/python3.8/site-packages/VenC-2.0.0-py3.8.egg/EGG-INFO/scripts/venc", line 88, in <module>
>   File "/home/jeremy/.local/lib/python3.8/site-packages/VenC-2.0.0-py3.8.egg/EGG-INFO/scripts/venc", line 80, in argv_handler
>   File "/home/jeremy/.local/lib/python3.8/site-packages/VenC-2.0.0-py3.8.egg/venc2/commands/export.py", line 190, in export_blog
>   File "/home/jeremy/.local/lib/python3.8/site-packages/VenC-2.0.0-py3.8.egg/venc2/commands/export.py", line 161, in process\_non\_contextual\_patterns
>   File "/home/jeremy/.local/lib/python3.8/site-packages/VenC-2.0.0-py3.8.egg/venc2/patterns/processor.py", line 456, in process
>   File "/home/jeremy/.local/lib/python3.8/site-packages/VenC-2.0.0-py3.8.egg/venc2/patterns/processor.py", line 326, in run_pattern
>   File "/home/jeremy/.local/lib/python3.8/site-packages/VenC-2.0.0-py3.8.egg/venc2/datastore/\_\_init\_\_.py", line 643, in get\_entry\_title
> IndexError: list index out of range

The _IndexError_ indication is a bit esoteric and seeing line 643 of the **\_\_init\_\_.py** file doesn't help much. Catching the error to display a VenC more explicit message might be more convenient for other neophytes who want to develop their template as well. It could be something like:

> Pattern `.:GetEntryTitle:.` used out of its context. It could happen when your blog is exported and you have at least one pattern used out of its context in your template. You could modify your template to use conditional pattern to specify when to use context-dependant pattern. More information in the documentation at URL.

Thanks you for your time and keep up the good work !

**Comment by DenisSalem** [comment]
Should be fixed
