### ISSUE TITLE
ASCIIdoc support

### ISSUE THREAD

**Issue by YanTHIERY** [DenisSalem/VenC#24]
Hello there,

Is VenC going to support [ASCIIdoc](https://docs.asciidoctor.org/asciidoc/latest/) as writing format ?

Bye :)

**Comment by DenisSalem** [comment]
I will investigate to integrate such feature.

An upcomming release of v2.1.0 is planned very soon. Stay tunned.

**Comment by YanTHIERY** [comment]
OK thanks :smiley:

**Comment by DenisSalem** [comment]
https://gitlab.com/asciidoc3/asciidoc3/-/issues/5

**Comment by DenisSalem** [comment]
Asciidoc has been integrated in upcoming VenC v2.1.0
