### ISSUE TITLE
Kroki support

### ISSUE THREAD

**Issue by YanTHIERY** [DenisSalem/VenC#25]
Hello,

I'm curious, Can VenC add a support for [Kroki](https://kroki.io/) ?
The goal is to make VenC use Kroki API to convert text based diagrams to images on the fly.

Have a nice day,
Rollniak

**Comment by YanTHIERY** [comment]
Thx :smiley:

**Comment by DenisSalem** [comment]
Kroki has been integrated to VenC properly. Wait for the upcoming VenC release to see :)
