### ISSUE TITLE
[VenC Website] Animated images accessibility 

### ISSUE THREAD

**Issue by rollniak** [DenisSalem/VenC#26]
Hi,

The [VenC presentation](https://denissalem.tuxfamily.org/VenC/Presentation/) is full of well done animated images.
But when you have difficulties with distraction like moving things, it's more difficult to read the content of this page.
What can we do here ?

**Comment by DenisSalem** [comment]
Froze the image, animate when hovered.

**Comment by YanTHIERY** [comment]
Looks good for me

**Comment by DenisSalem** [comment]
New documentation fully readable in tty and w3c compliant has been made. There is no more flicking images.
